# TODO: check, looks like this is not working
services:
    # AI Gateway and AI Service Use Log services
    App\Service\AiGatewayService:
        calls:
            - [setAiServiceUseLogService, ['@App\Service\AiServiceUseLogService']]
            - [setAiUserSettingsService, ['@App\Service\AiUserSettingsService']]
            
    App\Service\AiServiceUseLogService:
        calls:
            - [setAiGatewayService, ['@App\Service\AiGatewayService']]
