framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
            # Uncomment if we add crowdin or other translation providers in future
            # crowdin:
            #     dsn: '%env(CROWDIN_DSN)%'
